[package]
name = "octavo"
version = "0.1.0"
authors = ["Łukasz Niemier <lukasz@niemier.pl>"]

description = "Highly modular crypto & hash library written in pure Rust"
license = "MIT"
repository = "https://github.com/hauleth/octavo"

[dependencies]
byteorder = "*"
rustc-serialize = "*"

[dependencies.clap]
version = "1.4"
optional = true

[dependencies.num]
version = "*"
optional = true

[dependencies.rand]
version = "*"
optional = true

[features]
default = [
  "digest",
  "crypto",
  "ssl",
  "tools"
]
unstable = []

tools = ["clap"]

digest = [
  "digest-deprecated",
  "digest-safe"
]

# Deprecated algorithms that are not considered safe enough to use in secure
# manner.
digest-deprecated = [
  "md4",
  "md5",
  "ripemd",
  "sha1",
]
digest-safe = [
  "sha2",
  "sha3",
]
md4 = []
md5 = []
ripemd = []
sha1 = []
sha2 = []
sha3 = []
# whirlpool = []
# tiger = []

crypto = [
  "symmetric",
  "public-key"
]

symmetric = [
  "block",
  "stream"
]

block = [
  "blowfish"
]
# aes = []
blowfish = []
# des = []
# serpent = []
# triple-des = []
# twofish = []
# idea = []

stream = [
  "chacha20"
]
# rc2 = []
# rc3 = []
# rc4 = []
# rabbit = []
# salsa20 = []
chacha20 = []
# hc-256 = []

public-key = [
  "rsa"
]
# dh = ["diffie-hellman"]
# diffie-hellman = ["rand"]
# ecc = ["rand"]
# elgamal = ["rand"]
rsa = ["num", "rand"]

mac = [
  "hmac"
]
hmac = []

ssl = []
