[package]
authors = ["Łukasz Jan Niemier <lukasz@niemier.pl>"]
homepage = "http://liboctavo.github.io/"
documentation = "http://liboctavo.github.io/octavo"
repository = "https://github.com/libOctavo/octavo"
readme = "README.md"
name = "octavo"
description = "Highly modular crypto & hash library written in pure Rust. WARNING!!! Not suitable for production."
keywords = [
  "cryptography", "hash", "meta"
]
license = "MIT"
version = "0.1.1"

[dependencies]

[dependencies.octavo-crypto]
path = "./crypto"
version = "0.1.0"

[dependencies.octavo-digest]
path = "./digest"
version = "0.1.0"

[dependencies.octavo-kdf]
path = "./kdf"
version = "0.1.0"

[dependencies.octavo-mac]
path = "./mac"
version = "0.1.0"

[dev-dependencies]
openssl = "0.7.5"
quickcheck = "0.2.24"

[features]
unstable = []
