[package]
authors = ["Łukasz Niemier <lukasz@niemier.pl>"]
description = "Highly modular crypto & hash library written in pure Rust"
documentation = "http://liboctavo.github.io/octavo"
license = "MIT"
name = "octavo"
repository = "https://github.com/libOctavo/octavo"
version = "0.1.0"

[dependencies]

[dependencies.octavo-crypto]
path = "./crypto"

[dependencies.octavo-digest]
path = "./digest"

[dependencies.octavo-kdf]
path = "./kdf"

[dependencies.octavo-mac]
path = "./mac"

[dev-dependencies]
openssl = "0.7.5"
quickcheck = "0.2.24"
