[package]
name = "octavo"
version = "0.1.0"
authors = ["Łukasz Niemier <lukasz@niemier.pl>"]

description = "Highly modular crypto & hash library written in pure Rust"
license = "MIT"
repository = "https://github.com/hauleth/octavo"

[dependencies]
byteorder = "*"

[dependencies.num]
version = "*"
optional = true

[features]
default = [
  "digest",
  "crypto",
  "ssl"
]
unstable = ["default"]

digest = [
  "digest-fast",
  "digest-deprecated",
  "digest-safe"
]

# Fast algorithms that aren't safe in any way.
digest-fast = [
  "adler32",
  "crc32"
]
# Deprecated algorithms that are not considered safe enough to use in secure
# manner.
digest-deprecated = [
  "md4",
  "md5",
  "sha1",
]
digest-safe = [
  "sha2",
  "sha3",
]
adler32 = []
crc32 = []
md4 = []
md5 = []
sha1 = []
sha2 = []
sha3 = []
# xxhash = []
# whirlpool = []
# tiger = []
# ripemd = []

crypto = [
  "symmetric",
  "public-key"
]

symmetric = [
  "blowfish"
]
# aes = []
blowfish = []
# des = []
# serpent = []
# triple-des = []
# twofish = []
# idea = []

# block = []
# rc2 = []
# rc3 = []
# rc4 = []
# rabbit = []
# salsa20 = []
# chacha = []
# hc-256 = []

public-key = []
# dh = ["diffie-hellman"]
# diffie-hellman = []
# ecc = []
# elgamal = []
# rsa = ["num"]

mac = [
  "hmac"
]
hmac = []

ssl = []
